#!/bin/bash

source bin/common

HOSTS=`cat conf/hosts.conf`

if [[ $1 == "sync" ]]; then
  $SYNC
fi
if [[ $1 == "check" ]]; then
  $JUDGE
fi
if [[ $1 == "report" ]]; then
  $REPORT
fi
if [[ $1 == "" ]]; then
  $SYNC
  if [[ $? == 0 ]]; then
    echo
    $JUDGE
  fi
fi

exit
