#!/bin/bash

JUDGE=bin/judge
CHECK=bin/check
COMPILE=bin/compile
SYNC=bin/sync
REPORT=bin/report
CLEANUP=bin/cleanup
SOLUTIONS_DIR=solutions
PROBLEMS_DIR=problems

source bin/common

HOSTS=`cat conf/hosts.conf`

if [[ $1 == "sync" ]]; then
  $SYNC
fi
if [[ $1 == "check" ]]; then
  $JUDGE
fi
if [[ $1 == "report" ]]; then
  $SYNC > /dev/null 2>&1
  if [[ $? == 0 ]]; then
    $REPORT
  fi
fi
if [[ $1 == "" ]]; then
  $SYNC
  if [[ $? == 0 ]]; then
    echo
    $JUDGE
  fi
fi

exit
