#!/bin/bash

JUDGE=bin/judge
COMPILE=bin/compile
CLEANUP=bin/cleanup
SOLUTIONS_DIR=solutions
PROBLEMS_DIR=problems

source bin/common

if [[ $PROBLEMS == "" ]]; then
  PROBLEMS=$@
fi

if [[ $PROBLEMS == "" ]]; then
  PROBLEMS=`ls -v -m1 $PROBLEMS_DIR`
fi

HOSTS=`cat conf/hosts.conf`


for host in $HOSTS; do
  hostdir=`echo $host | sed 's/:.*//'`
  mkdir -p $SOLUTIONS_DIR/$hostdir > /dev/null 2>&1
  rsync -r "$host/" $SOLUTIONS_DIR/$hostdir
  echo [HOST] $hostdir
  for problem in $PROBLEMS; do
    $COMPILE $SOLUTIONS_DIR/$hostdir/$problem/$problem.cpp $problem
    if [[ $? == 0 ]]; then
      $JUDGE $problem
    else
      echo
    fi
  done
done
